### ISSUE TITLE
Is this simpler?

### ISSUE THREAD

**Issue by DrGo** [dc0d/clarg#2]
Hello,
Thanks for sharing your nice code.
I copied and pasted it and made few changes that I am sharing with you in case you find useful.
1) got rid of reflection by using FlagSet.Name() to get the command name
2) replaced the loop with the following code 
```	
       flagSet, found := cmdTable[args[0]] //retrieve the FlagSet for this subcommand
	if !found {
		return nil, fmt.Errorf("command %v is not defined", args[0])
	}
	if err := flagSet.Parse(args[1:]); err != nil { //parse the armaments for this flag
		return nil, err
	}
	return flagSet, nil
```
3) for more flexibility, made it return a pointer to the found FlagSet instead of just the command name, so the caller can do thing like retrieving for non-flag arguments.

Thanks,

/salah

**Comment by dc0d** [comment]
Thanks Salah!

1 - Valid point. At the time of writing this, `*flag.FlagSet` had not a `Name()` method.
2 - Valid point - this was some legacy code of a time I was abusing it for accepting multiple sub-commands.
3 - Valid point. Because now the `*flag.FlagSet` has the `Name()` method.

I'll close this when the changes got applied.

**Comment by dc0d** [comment]
Code changed accordingly and because of breaking API a new version branch created, now available at:

```
$ go get -u -v github.com/dc0d/clarg
```

or

```
$ go get -u -v gopkg.in/dc0d/clarg.v3
```
